import asyncio
import logging
import uuid
import sys

# Configure logging to see the pipeline clearly
logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(name)s | %(message)s")
logger = logging.getLogger("Simulator")

# Import the initialized bus
from app.gateway.event_bus import bus

# Import all services so they subscribe to the bus
import app.gateway.abandonment_detector
import app.services.identity_service
import app.services.recovery_eligibility
import app.services.call_orchestrator
import app.services.policy_engine
import app.services.payment_execution
import app.services.email_service
import app.services.attribution

async def run_happy_path():
    logger.info("=== STARTING DETERMINISTIC HAPPY PATH TEST ===")
    
    correlation_id = f"corr_{uuid.uuid4().hex[:6]}"
    merchant_id = "jiva_demo"
    checkout_id = f"chk_{uuid.uuid4().hex[:6]}"
    customer_id = "cust_123"

    # 1. Trigger Abandonment Detector (Demo mode: waits 10s)
    # To speed up the test, we'll bypass the 10s wait and directly emit abandoned
    logger.info("1. Simulating checkout.abandoned (Bypassing 10s wait for test)")
    await bus.publish(
        event_type="checkout.abandoned",
        payload={
            "checkout_id": checkout_id,
            "customer_id": customer_id,
            "amount": 3499.0,
            "currency": "INR",
            "product_ids": ["sku_lamp_01"]
        },
        correlation_id=correlation_id,
        merchant_id=merchant_id,
        idempotency_key=f"abandonment_v1_{checkout_id}"
    )
    
    # Allow Event Bus to process async callbacks
    await asyncio.sleep(0.5)

    # 2. Simulate Customer Intel extracting meaning from the call
    logger.info("2. Simulating Customer Intelligence parsing speech mid-call")
    # In a real run, this happens after call.started
    
    # We need the recovery_attempt_id generated by the orchestrator. Let's pull it from the bus logs.
    recent_events = bus.get_recent_events(100)
    call_started_event = next((e for e in recent_events if e["event_type"] == "call.started"), None)
    
    if not call_started_event:
        logger.error("Test Failed: Orchestrator did not emit call.started")
        return
        
    recovery_attempt_id = call_started_event["payload"]["recovery_attempt_id"]
    logger.info(f"Retrieved active recovery attempt: {recovery_attempt_id}")

    await bus.publish(
        event_type="customer.understood",
        payload={
            "recovery_attempt_id": recovery_attempt_id,
            "checkout_id": checkout_id,
            "customer_id": customer_id,
            "intent": "purchase_interest",
            "barrier": "price",
            "customer_words": "It's too expensive yaar",
            "next_action": "request_offer",
            "requested_discount": 12.0 # The LLM asks for 12%
        },
        correlation_id=correlation_id,
        merchant_id=merchant_id,
        idempotency_key=f"intel_{recovery_attempt_id}"
    )

    await asyncio.sleep(0.5)

    # 3. Verify Payment Execution & WhatsApp
    recent_events = bus.get_recent_events(100)
    wa_event = next((e for e in recent_events if e["event_type"] == "whatsapp.sent"), None)
    if not wa_event:
        logger.error("Test Failed: WhatsApp was never sent")
        return
    
    # 4. Simulate Customer paying via Razorpay
    logger.info("3. Simulating Razorpay Webhook (Customer paid the link)")
    await bus.publish(
        event_type="payment.succeeded",
        payload={
            "amount": 321908, # Paise for ~8% off 3499
            "notes": {
                "recovery_attempt_id": recovery_attempt_id,
                "checkout_id": checkout_id
            }
        },
        correlation_id=correlation_id,
        merchant_id=merchant_id,
        idempotency_key=f"rzp_{recovery_attempt_id}"
    )

    await asyncio.sleep(0.5)

    # 5. Verify Attribution
    recent_events = bus.get_recent_events(100)
    attr_event = next((e for e in recent_events if e["event_type"] == "revenue.attributed"), None)
    
    if attr_event:
        logger.info("=== TEST SUCCESS: Deterministic Pipeline Executed Perfectly ===")
        logger.info(f"Attributed Revenue: INR {attr_event['payload']['amount']}")
    else:
        logger.error("=== TEST FAILED: Revenue was not attributed ===")

async def run_failure_test_opt_out():
    logger.info("=== STARTING FAILURE TEST: OPT-OUT ===")
    
    correlation_id = f"corr_{uuid.uuid4().hex[:6]}"
    recovery_attempt_id = f"rec_mock_{uuid.uuid4().hex[:6]}"

    logger.info("Simulating customer saying 'Don't call me'")
    await bus.publish(
        event_type="customer.understood",
        payload={
            "recovery_attempt_id": recovery_attempt_id,
            "next_action": "opt_out",
        },
        correlation_id=correlation_id,
        merchant_id="jiva_demo",
    )
    
    await asyncio.sleep(0.2)
    # The orchestrator should have transitioned to OPTED_OUT and halted.
    recent_events = bus.get_recent_events(10)
    wa_event = next((e for e in recent_events if e["event_type"] == "whatsapp.send_requested" and e["correlation_id"] == correlation_id), None)
    
    if wa_event:
        logger.error("Test Failed: WhatsApp sent to opted out user")
    else:
        logger.info("=== TEST SUCCESS: Opt-Out respected, execution halted ===")

async def main():
    await run_happy_path()
    print("\n")
    await run_failure_test_opt_out()
    
    # Note: Failure Case 1 (paid during wait) is handled intrinsically by abandonment_detector atomic DB check.
    # Note: Failure Case 3 (Duplicate WA) is handled by the Idempotency Set in whatsapp_service.py.

if __name__ == "__main__":
    asyncio.run(main())
