import asyncio
import logging
import uuid
import os
import sys

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(name)s | %(levelname)s | %(message)s")
logger = logging.getLogger("WOW_DEMO")

from app.gateway.event_bus import bus

# Import all services to wire them to the bus
import app.gateway.abandonment_detector

# This script speeds up the abandonment window for its own interactive run -
# not a product-level "demo mode" flag. The real default (1800s) lives in
# app/gateway/abandonment_detector.py.
app.gateway.abandonment_detector.ABANDONMENT_WINDOW = 10

import app.services.identity_service
import app.services.recovery_eligibility
import app.services.call_orchestrator
import app.services.customer_intelligence
import app.services.policy_engine
import app.services.payment_execution
import app.services.email_service
import app.services.attribution

event_tracker = []

async def intercept_all(event: dict):
    """Hooks every event to generate the WOW log trace and track assertions."""
    event_type = event.get("event_type")
    event_tracker.append(event_type)
    
    # Pretty-print the WOW moments
    if event_type == "checkout.abandoned":
        logger.info(f"\n[WOW] \u26A0\uFE0F Jiva \u2014 \u20B93,499 checkout abandoned. Identity and Consent verified.\n")
    elif event_type == "call.started":
        logger.info(f"\n[WOW] \ud83d\udcde Kinato is calling the customer...\n")
    elif event_type == "voice.turn_completed":
        logger.info(f"\n[WOW] \ud83d\udde3\uFE0F Customer says: \"{event['payload']['transcript']}\"\n")
    elif event_type == "customer.understood":
        payload = event['payload']
        logger.info(f"\n[WOW] \ud83e\udde0 Kinato understands:\n      Barrier: {payload['barrier']}\n      Temperature: {payload['temperature']}\n      Next Action: {payload['next_action']}\n")
    elif event_type == "email.send_requested":
        logger.info(f"\n[WOW] \ud83d\udce7 Recovery checkout email sent dynamically mid-call (Discount: {event['payload']['discount']}%)\n")
    elif event_type == "payment.succeeded":
        logger.info(f"\n[WOW] \ud83d\udcb3 Customer paid Razorpay link!\n")
    elif event_type == "revenue.attributed":
        logger.info(f"\n[WOW] \ud83c\udfaf KINATO-ATTRIBUTED REVENUE: \u20B9{event['payload']['amount']}\n")

# Subscribe to everything using a wildcard-like pattern
# Actually, since our EventBus requires exact string matching, we'll just inject our tracker.
original_publish = bus.publish
async def patched_publish(event_type, payload, correlation_id, merchant_id, idempotency_key=None):
    event_dict = {
        "event_type": event_type, 
        "payload": payload,
        "correlation_id": correlation_id,
        "merchant_id": merchant_id,
        "idempotency_key": idempotency_key
    }
    await intercept_all(event_dict)
    await original_publish(event_type, payload, correlation_id, merchant_id, idempotency_key)

bus.publish = patched_publish


async def run_golden_path():
    logger.info("=== STARTING PHASE 6: GOLDEN PATH E2E INTEGRATION ===")
    
    checkout_id = f"chk_{uuid.uuid4().hex[:6]}"
    customer_id = "cust_123"
    merchant_id = "jiva_demo"
    correlation_id = checkout_id

    # 1. Simulate the merchant SDK initiating the checkout
    logger.info("--> Merchant SDK: Kinato.track('checkout.started')")
    await bus.publish(
        event_type="checkout.started",
        payload={
            "checkout_id": checkout_id,
            "customer_id": customer_id,
            "cart_id": "cart_999",
            "amount": 3499.0,
            "currency": "INR",
            "product_ids": ["sku_lamp_01"]
        },
        correlation_id=correlation_id,
        merchant_id=merchant_id
    )

    # 2. Wait for the abandonment detector (window sped up above to 10s)
    logger.info("--> Waiting 11 seconds to prove real-time Abandonment Detector & Eligibility checks...")
    await asyncio.sleep(11)
    
    # 3. Verify the Orchestrator started the call
    if "call.started" not in event_tracker:
        logger.error("❌ FAILED: call.started was not reached after 10s.")
        return
        
    # Extract the recovery attempt ID generated by the orchestrator
    call_events = [e for e in bus.get_recent_events(100) if e["event_type"] == "call.started"]
    recovery_attempt_id = call_events[0]["payload"]["recovery_attempt_id"]

    # 4. Simulate Twilio capturing customer speech
    logger.info("--> Twilio STT: Turn Completed")
    await bus.publish(
        event_type="voice.turn_completed",
        payload={
            "call_id": f"call_{uuid.uuid4().hex[:6]}",
            "recovery_attempt_id": recovery_attempt_id,
            "transcript": "It's too expensive yaar."
        },
        correlation_id=correlation_id,
        merchant_id=merchant_id
    )
    
    # Wait for Intel -> Policy -> Payment -> Email
    await asyncio.sleep(6)

    if "email.send_requested" not in event_tracker:
        logger.error("❌ FAILED: email.send_requested was not reached.")
        return

    # 5. Simulate Razorpay Webhook arrival
    logger.info("--> Razorpay Webhook: payment.succeeded")
    await bus.publish(
        event_type="payment.succeeded",
        payload={
            "amount": 321908, # Paise
            "checkout_id": checkout_id,
            "recovery_attempt_id": recovery_attempt_id,
            "notes": {
                "recovery_attempt_id": recovery_attempt_id,
                "checkout_id": checkout_id
            }
        },
        correlation_id=correlation_id,
        merchant_id=merchant_id
    )
    
    await asyncio.sleep(1)
    
    if "revenue.attributed" not in event_tracker:
        logger.error("❌ FAILED: revenue.attributed was not reached.")
        return
        
    logger.info("\n=== INTEGRATION TEST COMPLETE ===")
    logger.info("Event Lifecycle Validated:")
    for event in event_tracker:
        logger.info(f" \u2714\uFE0F {event}")

if __name__ == "__main__":
    asyncio.run(run_golden_path())
